In [3]:
import torch
import torch.nn as nn

# We Define an input of 2 batch with 5 columns which be send through a linear layer in ANN which will output a 5x6 with Relu activation 

In [4]:
torch.manual_seed(123)
inputs = torch.randn(2,5)
layer = nn.Sequential(nn.Linear(5,6), nn.ReLU())
output= layer(inputs)

In [6]:
output.shape

torch.Size([2, 6])

In [7]:
mean = output.mean(dim=1,keepdim=True)
var = output.var(dim=1,keepdim=True)

In [8]:
mean

tensor([[0.1324],
        [0.2170]], grad_fn=<MeanBackward1>)

In [9]:
var

tensor([[0.0231],
        [0.0398]], grad_fn=<VarBackward0>)

# This is the formula for Layer Norm 

In [10]:
output_norm = (output - mean)/ torch.sqrt(var)

In [11]:
output_norm

tensor([[ 0.6159,  1.4126, -0.8719,  0.5872, -0.8719, -0.8719],
        [-0.0189,  0.1121, -1.0876,  1.5173,  0.5647, -1.0876]],
       grad_fn=<DivBackward0>)

In [ ]:
output_norm.var(dim=1, keepdim=True)

tensor([[1.0000],
        [1.0000]], grad_fn=<VarBackward0>)

In [17]:
output_norm.mean(dim=1, keepdim=True)


tensor([[9.9341e-09],
        [0.0000e+00]], grad_fn=<MeanBackward1>)

In [19]:
# Mean of the output norm was no exact to zero because of some error in calculation in python
# so we set the printoptions so now we get the mean exact to zero
torch.set_printoptions(sci_mode=False)

In [22]:
output_norm.mean(dim=1, keepdim=True)
#As you can see we have success fully acheived a  layer norm functionality 
# with a standard deviation of 1 and a mean of 0

tensor([[    0.0000],
        [    0.0000]], grad_fn=<MeanBackward1>)

# This Layer Norm we achieved will help to resolve two issues while trainin:
1. It will help to converge the training much more faster 
2. Instability in learning meaning can help in reduce the problem of vanishing as well as exploding gradients problem